pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Aparnadevi-lab/sql-wrapping.git'
            }
        }

        stage('Wrap SQL Files') {
            steps {
                bat 'python scripts\\wrap_sql.py'
            }
        }

        stage('Archive Results') {
            steps {
                archiveArtifacts artifacts: 'output_sql/*', fingerprint: true
            }
        }
    }
}

